print("--------------Food Bill---------------")
print("Food Item\tQuantity\tPrice")
print("Rolls\t\t3\t\t150")
print("Burger\t\t2\t\t100")
print("Coffee\t\t2\t\t250")
print("--------------------------------------")
print("Total:\t\t\t\t500")
print("--------------------------------------")