name=input("Enter your name: ")
print("1st operation, Uppercase: ",name.upper())
print("2nd operation, Lowercase: ",name.lower())
print("3rd operation, Without extra Sidespaces: ",name.strip())
print("4th operation, length: ", len(name))